[colors]
    keyword_color = 0xFB4934FF
    secondary_keyword_color = 0xFE8019FF
    symbol_color = 0x8EC07CFF
    string_literal_double_color = 0xD3896BFF
    string_literal_single_color = 0xF2CE00FF
    number_color = 0xD3896BFF
    built_in_type_color = 0xFE8019FF
    type_color = 0xFABD2FFF
    function_name_color = 0x8EC07CFF
    comment_single_color = 0x928374FF
    comment_multi_color = 0x928374FF
    foreground_color = 0xFBF1C7FF
    background_color = 0x282828FF
    highlight_color = 0x303F34FF