[general]
    foreground = 0xFBF1C7FF
    background = 0x1D2021FF
    current_line = 0x292929FF
    user_selection = 0x303F34FF
    gutter_foreground = 0x665C54FF
[syntax]
    keyword = 0xFB4934FF
    secondary_keyword = 0xFE8019FF
    built_in_type = 0xFE8019FF
    type = 0xFABD2FFF
    function_name= 0x8EC07CFF
    symbol = 0x8EC07CFF
    double_quote_string = 0xD3896BFF
    single_quote_string = 0xD3896BFF
    number = 0xD3896BFF
    single_line_comment = 0x928374FF
    multiline_comment = 0x928374FF