[general]
    foreground = 0xECf0C1FF
    background = 0x0F111BFF
    current_line = 0x16172DFF
    user_selection = 0x30365FFF
    gutter_foreground = 0x30365FFF
[syntax]
    keyword = 0x7A5CCCFF
    secondary_keyword = 0xB3A1E6FF
    built_in_type = 0x5CCC96FF
    type = 0xF2CE00FF
    function_name= 0x5CCC96FF
    symbol = 0xCE6F8FFF
    double_quote_string = 0x00A3CCFF
    single_quote_string = 0xF2CE00FF
    number = 0xF2CE00FF
    single_line_comment = 0x686f9aFF
    multiline_comment = 0x686f9aFF