[highlighting]
    keywords = ["and", "as", "assert", "break", "class", "continue", "def", "del", "elif", "else", "except", "False", "finally", "for", "from", "global", "if", "import", "in", "is", "lambda", "None", "nonlocal", "not", "or", "pass", "raise", "return", "True", "try", "while", "with", "yield"]
    symbols = [ "(", ")", "[", "]", "{", "}", "*", "=", "|", "&", "!", "%", "-", "+", "/", "?", "<", ">", ":" ]
    preprocessor_directives = []
    comment_single_prefix = "#"
    comment_multi_begin = "/*"
    comment_multi_end = "*/"
    enable_identifier_heuristics = true