[general]
    font = "./fonts/iosevka-firamono.ttf"
    theme = "./config/themes/spaceduck.toml"

    # font size in pixels
    font_size = 24

    # displays an fps counter in the bottom right corner (debug)
    show_fps = true

[editor]
    # how many characters a tab is worth
    tab_stop = 3

    # visual animation speed for cursor
    cursor_speed = 6.5

    # In lines per scroll unit
    scroll_speed = 2
    
    # Controls how far from the top/bottom the cursor needs to be
    # before scrolling the buffer (arrow keys)
    scroll_stop_top = 6
    scroll_stop_bottom = 2

# Keybinds

[keybind.global.openBrowser]
    key = "o"
    mods = ["control"]
[keybind.global.reloadConfig]
    key = "f5"
[keybind.global.returnToEditor]
    key = "escape"


[keybind.editor.moveRight]
    key = "right"
[keybind.editor.selectRight]
    key = "right"
    mods = ["shift"]
[keybind.editor.moveForwardWord]
    key = "right"
    mods = ["control"]
[keybind.editor.selectForwardWord]
    key = "right"
    mods = ["shift", "control"]

[keybind.editor.moveLeft]
    key = "left"
[keybind.editor.selectLeft]
    key = "left"
    mods = ["shift"]
[keybind.editor.moveBackwardWord]
    key = "left"
    mods = ["control"]
[keybind.editor.selectBackwardWord]
    key = "left"
    mods = ["shift", "control"]

[keybind.editor.moveUp]
    key = "up"
[keybind.editor.selectUp]
    key = "up"
    mods = ["shift"]

[keybind.editor.moveDown]
    key = "down"
[keybind.editor.selectDown]
    key = "down"
    mods = ["shift"]

[keybind.editor.deleteLeft]
    key = "backspace"
[keybind.editor.deleteWordLeft]
    key = "backspace"
    mods = ["control"]

[keybind.editor.deleteRight]
    key = "delete"
[keybind.editor.deleteWordRight]
    key = "delete"
    mods = ["control"]

[keybind.editor.write]
    key = "s"
    mods = ["control"]

[keybind.editor.openSaveDialog]
    key = "s"
    mods = ["control", "shift"]

[keybind.editor.unselect]
    key = "escape"

[keybind.browser.decrementSelection]
    key = "up"
[keybind.browser.incrementSelection]
    key = "down"
[keybind.browser.openSelection]
    key = "enter"

[keybind.save.moveRight]
    key = "right"
[keybind.save.moveLeft]
    key = "left"
[keybind.save.deleteLeft]
    key = "backspace"
[keybind.save.submitSaveDialog]
    key = "enter"

[keybind.editor.openNewFile]
    key ="n"
    mods = ["control"]