[general]
    font = "./fonts/iosevka-firamono.ttf"
    theme = "./config/themes/spaceduck.toml"

    # font size in pixels
    font_size = 22

    # displays an fps counter in the bottom right corner (debug)
    show_fps = false

[editor]
    # how many characters a tab is worth
    tab_stop = 3

    # visual animation speed for cursor
    cursor_speed = 6.5

    # In lines per scroll unit
    scroll_speed = 2
    
    # Controls how far from the top/bottom the cursor needs to be
    # before scrolling the buffer (arrow keys)
    scroll_stop_top = 6
    scroll_stop_bottom = 2

[keybind.test]
    key = "1"
    mods = ["control"]

[keybind.move_right]
    key = "f7"
    mods = []