[general]
    font = "./fonts/iosevka-firamono.ttf"
    theme = "./config/themes/spaceduck.toml"

    # font size in pixels
    font_size = 22

    # displays an fps counter in the bottom right corner (debug)
    show_fps = false

[editor]
    # how many characters a tab is worth
    tab_stop = 3

    # visual animation speed for cursor
    cursor_speed = 6.5

    # In lines per scroll unit
    scroll_speed = 2
    
    # Controls how far from the top/bottom the cursor needs to be
    # before scrolling the buffer (arrow keys)
    scroll_stop_top = 6
    scroll_stop_bottom = 2


# Keybinds
[keybind.moveRight]
    key = "right"
[keybind.selectRight]
    key = "right"
    mods = ["shift"]
[keybind.moveForwardWord]
    key = "right"
    mods = ["control"]
[keybind.selectForwardWord]
    key = "right"
    mods = ["shift", "control"]

[keybind.moveLeft]
    key = "left"
[keybind.selectLeft]
    key = "left"
    mods = ["shift"]
[keybind.moveBackwardWord]
    key = "left"
    mods = ["control"]
[keybind.selectBackwardWord]
    key = "left"
    mods = ["shift", "control"]

[keybind.moveUp]
    key = "up"
[keybind.selectUp]
    key = "up"
    mods = ["shift"]

[keybind.moveDown]
    key = "down"
[keybind.selectDown]
    key = "down"
    mods = ["shift"]

[keybind.deleteLeft]
    key = "backspace"
[keybind.deleteWordLeft]
    key = "backspace"
    mods = ["control"]

[keybind.deleteRight]
    key = "delete"
[keybind.deleteWordRight]
    key = "delete"
    mods = ["control"]

[keybind.openBrowser]
    key = "o"
    mods = ["control"]
[keybind.write]
    key = "s"
    mods = ["control"]
[keybind.closeBrowser]
    key = "escape"

[keybind.unselect]
    key = "escape"